### PUT request to update patients
PUT http://localhost:4000/patients/update/223e4567-e89b-12d3-a456-426614174011
Content-Type: application/json

{
  "name": "Ethan The Martinez",
  "email": "jethan.martinez@example.com",
  "address": "987 Redwood St, Springfield",
  "dateOfBirth": "1984-05-03"
}


###